sfswitch/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'enable_disable.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth_response/$', 'enable_disable.views.oauth_response', name='oauth_response'),
    url(r'^logout/$', 'enable_disable.views.logout', name='logout'),
    url(r'^loading/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'enable_disable.views.loading'),
    url(r'^job_status/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'enable_disable.views.job_status'),
    url(r'^job/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'enable_disable.views.job'),
    url(r'^update_metadata/(?P<job_id>[0-9A-Za-z_\-]+)/(?P<metadata_type>[0-9A-Za-z_\-]+)/$', 'enable_disable.views.update_metadata'),
    url(r'^check_deploy_status/(?P<deploy_job_id>\d+)/$', 'enable_disable.views.check_deploy_status'),
    url(r'^auth_details/$', 'enable_disable.views.auth_details'),
)

enable_disable/forms.py
from django import forms
from django.forms import ModelForm

class LoginForm(forms.Form):
	environment = forms.CharField(required=False)
	access_token = forms.CharField(required=False)
	instance_url = forms.CharField(required=False)
	username = forms.CharField(required=False)
	org_name = forms.CharField(required=False)
	org_id = forms.CharField(required=False)

sfswitch/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Salesforce.com Switch</title>
		<meta name="keywords" content="salesforce, salesforce.com, force.com, metadata, enable, disable, validation rules, validation, workflow, trigger" /> 
  		<meta name="description" content="Easily enable and disable Salesforce components - Workflows, Validation Rules and Triggers" />
  		<meta name="author" content="Ben Edwards (ben@benedwards.co.nz)" />
  		<meta charset="UTF-8" />

  		{% block css %}{% endblock %}
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/styles.css" />
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap-switch.min.css" />
		
		<!--
		<link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico" type="image/vnd.microsoft.icon" />
		-->
		
		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/main.js"></script>
		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-switch.min.js"></script>

		{% block scripts %}{% endblock %}

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-18288189-23', 'auto');
		  ga('send', 'pageview');

		</script>
	</head>	

	<body>

		{% if request.GET.noheader != '1' %}

			<!-- Static navbar -->
	      	<nav class="navbar navbar-default">

		        <div class="container-fluid">

		          	<div class="navbar-header">
		            	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			              	<span class="sr-only">Toggle navigation</span>
			              	<span class="icon-bar"></span>
			              	<span class="icon-bar"></span>
			              	<span class="icon-bar"></span>
		            	</button>
		          	</div>

		          	<div id="navbar" class="navbar-collapse collapse">

		          		<ul class="nav navbar-nav navbar-left">
		          			<li>
		          				<a href="/" style="padding:5px;">
		          					<img src="/static/images/logo-small.png" alt="Switch" border="0" />
		          				</a>
		          			</li>
		          			<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
		              		<li>
		            			<a href="http://sftoolkit.co/" target="_blank">Salesforce Toolkit</a>
		            		</li>
		            	</ul>

		            	<ul class="nav navbar-nav navbar-right">
		              		<li>
		              			<a href="https://github.com/benedwards44/sfswitch" target="_blank">Source Code</a>
		              		</li>
		              		<li>
		              			<a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
		              		</li>
		              		<li>
		              			<a href="#">
		              				<img src="/static/images/i-icon.png" data-toggle="modal" data-target="#infoModal" />
		              			</a>
		              		</li>
		            	</ul>

		          	</div><!--/.nav-collapse -->

		        </div><!--/.container-fluid -->

		    </nav>

			<div class="clear"></div>

			<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
				<div class="modal-dialog small_dialog">
			    	<div class="modal-content">
			      		<div class="modal-header">
			        		<button type="button" class="close" data-dismiss="modal">
			        			<span aria-hidden="true">&times;</span>
			        			<span class="sr-only">Close</span>
			        		</button>
			        		<h3 class="modal-title" id="apiModalLabel">
			        			Salesforce Switch
			        		</h3>
			      		</div>
			      		<div class="modal-body">
			        		<p>
			        			For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@benedwards.co.nz">ben@benedwards.co.nz</a>.
			        		</p>
			        		<p>
			        			I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
			        		</p>
			        		<p>
			        			If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
			        			<a href="http://sftoolkit.co/" target="_blank">http://sftoolkit.co/</a>
			        		</p>
			      		</div>
			      		<div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					    </div>
			    	</div>
			  	</div>
			</div>

		{% endif %}

		<div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">
			{% block content %}{% endblock %}
		</div>

	</body>

</html>

sfswitch/templates/index.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Switch</h1>
	<p>
		This tool provides an interface to easily enable and disable components in your Salesforce Org - Workflows, Triggers and Validation Rules. Very useful when doing data migrations and needing to disable certain automation.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>
	
	<div id="login_table">

		<form action="." method="POST" onsubmit="hideTable();" oncomplete="showTable();" id="loginForm"> 	
			{% csrf_token %}

			<table class="login_table">

				{% if messages %}
					<tr>
						<td colspan="3" style="color:#ff6600;font-weight:bold;">
						    {% for message in messages %}
						    	{{ message }}<br/>
						    {% endfor %}
						    <br/>
						</td>
					</tr>
				{% endif %}

				<tr>
					<td width="125">
						<label for="id_environment">Environment</label>
					</td>
					<td width="130">
						<select id="id_environment" name="environment" class="form-control" style="width:125px;">
							<option value="Production">Production</option>
							<option value="Sandbox">Sandbox</option>
						</select>
					</td>
					<td>
						<input type="submit" value="Login" />
					</td>
				</tr>

			</table>

			<div class="loading">
				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>
				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Accessing Salesforce...</h1>
					<p>Logging in with OAuth 2.0</p>
				</div>
			</div>

		</form>

	</div>

{% endblock %}

sfswitch/templates/loading.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Switch</h1>
	<p>
		This tool provides an interface to easily enable and disable components in your Salesforce Org - Workflows, Triggers and Validation Rules. Very useful when doing data migrations and needing to disable certain automation.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>
				
	<div class="loading-components">

		<div style="float:left;">
			<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">Querying metadata</h1>
			<p>Building a list of validation rules, workflows and triggers...</p>
		</div>

	</div>

	<div class="error" style="display:none;">
		<div class="alert alert-danger" role="alert">
			<p>
				There was an error processing your request: <i class="error_message"></i>
				<br/><br/>
				Please <a href="/{% if request.GET.noheader == '1' %}?noheader=1{% endif %}">return</a> to the home page and try again.
			</p>
		</div>
	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job_status/{{ job.random_id }}',
			    type: 'get', //this is the default though, you don't actually need to always mention it
			    dataType: 'json',
			    success: function(resp) 
			    {
			        if (resp.status == 'Finished')
			        {
			        	window.location = '/job/{{ job.random_id }}/{% if request.GET.noheader == "1" %}?noheader=1{% endif %}';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 3000);
	</script>

{% endblock %}

sfswitch/templates/logout.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Switch</h1>
	
	<div role="alert" class="alert alert-success">
		Successfully logged out of Salesforce and Switch
	</div>

	<iframe src="https://{{ instance_prefix }}.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

	<script>
		setTimeout(function () {
       		window.location.href = "/";
    	}, 3000);
	</script>

{% endblock %} 

sfswitch/templates/oauth_response.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Switch</h1>
	<p>
		This tool provides an interface to easily enable and disable components in your Salesforce Org - Workflows, Triggers and Validation Rules. Very useful when doing data migrations and needing to disable certain automation.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>
				
	<table id="login_table">

		<form action="." method="POST" id="loginForm"> 

			{% csrf_token %}

			<table class="login_table">

				{% if messages %}

					<tr>
						<td colspan="2" style="color:#ff6600;font-weight:bold;">
						    {% for message in messages %}
						    	{{ message }}<br/>
						    {% endfor %}
						    <br/>
						</td>
					</tr>
					
				{% endif %}

				{% if not error %}

					<h2>Logged in as:</h2>

					<tr>
						<td width="150">
							<strong>Username:</strong>
						</td>
						<td>
							{{ username }}
						</td>
					</tr>

					<tr>
						<td width="150">
							<strong>Organisation:</strong>
						</td>
						<td>
							{{ org_name }}
						</td>
					</tr>

					<tr height="30">
						<td colspan="2"></td>
					</tr>

					<tr>
						<td colspan="2" style="text-align:center;height:50px;">
							<input type="submit" name="logout" value="Logout" onclick="showLogout();" oncomplete="hideLogout();" />
							<input type="submit" name="get_metadata" value="Get Metadata" onclick="hideTable();" oncomplete="showTable();" />
						</td>
					</tr>

				{% else %}

				<tr>
					<td colspan="2">
						<div class="alert alert-danger" role="alert">
							<p>
								<strong>Error:</strong>  {{ error_message }}
							</p>
							<p>	
								Please go <a href="/">back</a> and try again.
							</p>
						</div>
					</td>
				</tr>

				{% endif %}

			</table>

			<div class="loading">

				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>

				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Querying metadata</h1>
					<p>Building a list of validation rules, workflows and triggers...</p>
				</div>
				
			</div>

			<div class="logging_out">

				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>

				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Logging out...</h1>
					<p>Revoking OAuth token.</p>
				</div>

			</div>

			<div style="display:none;">
				{{ login_form.as_p }}
			</div>

		</form>

	</table>

{% endblock %}